Develop
polytech-frontend-2017/Prokhorova_Pereverzev_course_project pull request #2
Opened 2017-10-26 15:48 UTC by Makcimus48

2017-10-26 16:05 UTC, Chudesnov commented on src/App.css
> +form{
Пустые правила надо убрать

2017-10-26 16:05 UTC, Chudesnov commented on src/js/StartMenu.js
> +        var form=e.target.parentNode.parentNode;
Обращаться к HTML-нодам без крайней необходимости (например, сделать getBoundingClientRect) нельзя, используй передачу данных напрямую из input через onChange / onInput в локальный стейт формы.

2017-10-26 16:05 UTC, Chudesnov commented on src/js/StartMenu.js
> +                    <p><input type="button" onClick={this.handlerCreateCompetition} value="Create Competition"/></p>
`<button type="submit">` и `onSubmit` на `form`

2017-10-26 16:05 UTC, Chudesnov commented on src/js/StartMenu.js
> +                    <span>Date:</span>
'<label for="...">'

2017-10-26 16:05 UTC, Chudesnov commented on src/js/Store.js
> +    addCompetition(Title,Date){
называется add, но перезаписывает параметры. Что имеется в виду?

2017-10-26 16:05 UTC, Chudesnov commented on src/js/Store.js
> +        this.competition = {title:Title, date:Date};
можно проще:
```
addCompetition(title, date) {
  this.competition = { title, date };
}
```

2017-10-26 16:05 UTC, Chudesnov commented on src/js/Store.js
> +export class Store {
как Store оповещает подписчиков об изменении данных?

2017-10-26 17:19 UTC, Makcimus48 commented on src/js/StartMenu.js
> +                    <p><input type="button" onClick={this.handlerCreateCompetition} value="Create Competition"/></p>
да, так и планируем сделать, когда подключим сервер и MySQL; пока форму сделали без submit , чтобы не обновлялась страница.

2017-10-26 17:22 UTC, Makcimus48 commented on src/js/Store.js
> +    addCompetition(Title,Date){
Как только появится сервер, эта функция превратиться в ajax запрос.

2017-10-26 17:22 UTC, Makcimus48 commented on src/js/Store.js
> +        this.competition = {title:Title, date:Date};
Спасибо!

2017-10-26 17:22 UTC, Makcimus48 commented on src/js/Store.js
> +export class Store {
Визуально

2017-10-26 18:06 UTC, Chudesnov commented on src/js/Store.js
> +export class Store {
Я имею в виду, как компоненты будут понимать, что данные обновились, и надо вызвать рендер?

2017-10-26 18:06 UTC, Chudesnov commented on src/js/StartMenu.js
> +                    <span>Date:</span>
Тут надо использовать label

2017-10-26 18:07 UTC, Chudesnov commented on src/js/StartMenu.js
> +                    <p><input type="button" onClick={this.handlerCreateCompetition} value="Create Competition"/></p>
На onSubmit  формы можно сделать preventDefault() и вызвать собственную логику, это совершенно нормальная практика.

2017-10-31 08:52 UTC, Chudesnov requested changes

2017-10-31 08:52 UTC, Chudesnov commented on src/context/connectDecorator.js
> +                    // return {
Лишние комментарии нужно убрать

2017-10-31 08:52 UTC, Chudesnov commented on src/App.js
> +/*<img src={logo} className="App-logo" alt="logo" />*/
эти тоже

2017-10-31 08:52 UTC, Chudesnov commented on src/App.js
> +                <StartMenu ></StartMenu>
что-то не то опять с отступами, настройте автоформатирование кода и стилей на pre-commit.

2017-10-31 08:52 UTC, Chudesnov commented on src/App.css
> +.container label {
Не пойдет, задайте уникальные классы для таких лейблов и не используйте каскад в CSS.

2017-11-21 15:08 UTC, Chudesnov requested changes

2017-11-21 15:08 UTC, Chudesnov commented on src/Lists.css
> +th {
надо проставить классы непосредственно в <th> и стили задавать для этого класса

2017-11-21 15:08 UTC, Chudesnov commented on src/Lists.css
> +    color:#666B85;
аналогично. глобально задавать в рамках компонента стили для всех элементов с определенным тегом нельзя

2017-11-21 15:08 UTC, Chudesnov commented on src/form.css
> +.formInput h1{
убрать каскад, проставить класс самому h1

2017-11-21 15:08 UTC, Chudesnov commented on src/header.css
> +a{
задать классы для ссылок и списков, глобальные стили (просто a, ul, li) не делать

2017-11-21 15:08 UTC, Chudesnov commented on src/js/CreateCompMenu.js
> +                            <input type="submit" value="Создать"/>
лучше `<button type='submit'>Создать</button>`

2017-11-21 15:08 UTC, Chudesnov commented on src/js/FormAddTournir.js
> +                    <input type="number" min={1} max={100} title={'Минимальный возраст'} required autoFocus
вместо title лучше использовать placeholder и aria-label

2017-11-21 15:08 UTC, Chudesnov commented on src/js/ListCompetitors.js
> +    changeSurname(event){
лучше сделать один общий метод set(name, value) и обработчик onChange/onInput, который будет из event.target получать и значение, и имя поля (<input name>)

2017-11-21 15:08 UTC, Chudesnov commented on src/js/FormAddTournir.js
> +                <p>Возраст:<br/>
Здесь нужен либо `<fieldset>`, если полей несколько, либо `<label>`, если поле одно.

2017-11-21 15:08 UTC, Chudesnov commented on src/js/MenuHeader.js
> +import '../header.css';
делить js и css по папкам не лучшая идея, лучше группировать по компонентам и называть css и js файлы одинаково (MenuHeader.js/MenuHeader.css)

2017-11-21 15:08 UTC, Chudesnov commented on src/js/MenuHeader.js
> +                    <div className={'verticalLine'}/>
{} необязательны, если значение - простая строка

2017-11-21 15:08 UTC, Chudesnov commented on src/js/MenuHeader.js
> +                            <div key={i} className={'conteiner-li'}>
key={i} можно использовать только если список статичный

2018-01-29 17:33 UTC, closed without merging